<TABLE BORDER="1" cellpadding="4" cellspacing="0">
<TR>
<TD ALIGN="CENTER" bgcolor="#666633">
<FONT FACE="arial" SIZE="-1" COLOR="white"><B>Футбол</B></FONT>
</TD></TR><TR><TD bgcolor="#FFFFCC">
	<table border="0" cellpadding="3" cellspacing="0" WIDTH="100%">  
	<form action="http://voter.land.ru/view.php?pl=21693" method="post">
	<input type="hidden" name="action" value="vote">
	<tr>
	<td COLSPAN=2>
	<B><font FACE="arial" SIZE="-1">За какой клуб Вы болеете?</font></B>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="CHECKBOX" NAME="vote_N1" VALUE="1">
	</td>
	<td>
	<font FACE="arial" SIZE="-1">Спартак</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="CHECKBOX" NAME="vote_N2" VALUE="2">
	</td>
	<td>
	<font FACE="arial" SIZE="-1">Динамо</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="CHECKBOX" NAME="vote_N3" VALUE="3">
	</td>
	<td>
	<font FACE="arial" SIZE="-1">Торпедо</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="CHECKBOX" NAME="vote_N4" VALUE="4">
	</td>
	<td>
	<font FACE="arial" SIZE="-1">ЦСКА</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="CHECKBOX" NAME="vote_N5" VALUE="5">
	</td>
	<td>
	<font FACE="arial" SIZE="-1">Локомотив</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="CHECKBOX" NAME="vote_N6" VALUE="6">
	</td>
	<td>
	<font FACE="arial" SIZE="-1">За другой клуб</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="CHECKBOX" NAME="vote_N7" VALUE="7">
	</td>
	<td>
	<font FACE="arial" SIZE="-1">Я не болею ни за кого</font>
	</td>
	</tr><tr>
		<td ALIGN="CENTER" COLSPAN="2">
	<input type="submit" value="Голосовать">
	</td>
	</tr>
	</form>
	</table>
</TD>
</TR><TR>
<TD ALIGN="CENTER" bgcolor="#FFFFCC">
<B><FONT FACE="arial" SIZE="-1">
<A HREF="http://voter.land.ru/view.php?pl=21693">Результаты голосования</A>
</FONT></B>
</TD>
</TR><TR>
<TD ALIGN="CENTER" bgcolor="#FFFFCC">
<B><FONT FACE="arial" SIZE="-1">
<A HREF="http://voter.land.ru/full.php?fl=lyceum1&pl=21693">Другие голосования на<BR>ВебЛоцман</A>
</FONT></B>
</TD>
</TR>
</TABLE>

                                                  <TABLE BORDER="1" cellpadding="4" cellspacing="0">
<TR>
<TD ALIGN="CENTER" bgcolor="#3366CC">
<FONT FACE="Verdana, Arial, Helvetica" COLOR="white"><B>Л?цейське опитування</B></FONT>
</TD></TR><TR><TD bgcolor="#F0F0DF">
	<table border="0" cellpadding="3" cellspacing="0" WIDTH="100%">  
	<form action="http://voter.land.ru/view.php?pl=21697" method="post">
	<input type="hidden" name="action" value="vote">
	<tr>
	<td COLSPAN=2>
	<B><font FACE="Verdana, Arial, Helvetica">З ким з вчител?в у тебе асоц?юється поняття - охоронець Л?ЦЕЙСЬКОГО ДУХУ?</font></B>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="1">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Тищенко Михайло Григорович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="2">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Караванова Тетяна Петр?вна</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="3">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Пшен?чка Пауль Францович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="4">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Майданик Олена Генад?вна</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="5">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Федоренко Л?на Миколаївна</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="6">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Березовський Андр?й Миколайович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="7">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Л?нчук Юр?й Степанович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="8">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Клим'юк ?ван ?лар?онович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="9">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Головко Стан?слав Петрович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="10">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Хтось другий...</font>
	</td>
	</tr><tr>
		<td ALIGN="CENTER" COLSPAN="2">
	<input type="submit" value="Голосовать">
	</td>
	</tr>
	</form>
	</table>
</TD>
</TR><TR>
<TD ALIGN="CENTER" bgcolor="#F0F0DF">
<B><FONT FACE="Verdana, Arial, Helvetica">
<A HREF="http://voter.land.ru/view.php?pl=21697">Результаты голосования</A>
</FONT></B>
</TD>
</TR><TR>
<TD ALIGN="CENTER" bgcolor="#F0F0DF">
<B><FONT FACE="Verdana, Arial, Helvetica">
<A HREF="http://voter.land.ru/full.php?fl=lyceum1&pl=21697">Другие голосования на<BR>Черн?вецький м?ський л?цей №1</A>
</FONT></B>
</TD>
</TR>
</TABLE>

                                                  <TABLE width="422" BORDER="1" cellpadding="4" cellspacing="0">
<TR>
<TD ALIGN="CENTER" bgcolor="#3366CC">
<FONT FACE="Verdana, Arial, Helvetica" COLOR="white"><B>Л?цейське опитування</B></FONT>
</TD></TR><TR><TD bgcolor="#F0F0DF">
	<table border="0" cellpadding="3" cellspacing="0" WIDTH="100%">  
	<form action="http://voter.land.ru/view.php?pl=21697" method="post">
	<input type="hidden" name="action" value="vote">
	<tr>
	              <td COLSPAN=2> <B><font FACE="Verdana, Arial, Helvetica">З яким 
                    з вчител?в у тебе асоц?юється поняття &quot;охоронець Л?ЦЕЙСЬКОГО 
                    ДУХУ&quot;?</font></B> </td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="1">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Тищенко Михайло Григорович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="2">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Караванова Тетяна Петр?вна</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="3">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Пшен?чка Пауль Францович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="4">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Майданик Олена Генад?вна</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="5">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Федоренко Л?на Миколаївна</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="6">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Березовський Андр?й Миколайович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="7">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Пшен?чка Пауль Францович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="8">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Клим'юк ?ван ?лар?онович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="9">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Головко Стан?слав Петрович</font>
	</td>
	</tr><tr>
	<td ALIGN="RIGHT">
	<INPUT TYPE="RADIO" NAME="vote_N" VALUE="10">
	</td>
	<td>
	<font FACE="Verdana, Arial, Helvetica">Хтось другий...</font>
	</td>
	</tr><tr>
		<td ALIGN="CENTER" COLSPAN="2">
	<input type="submit" value="Голосувати">
	</td>
	</tr>
	</form>
	</table>
</TD>
</TR><TR>
          <TD ALIGN="CENTER" bgcolor="#F0F0DF"> <B><FONT FACE="Verdana, Arial, Helvetica"> 
            <A HREF="http://voter.land.ru/view.php?pl=21697">Результати опитування</A> 
            </FONT></B> </TD>
</TR><TR>
          <TD ALIGN="CENTER" bgcolor="#F0F0DF"> <B><FONT FACE="Verdana, Arial, Helvetica"> 
            <A HREF="http://voter.land.ru/full.php?fl=lyceum1&pl=21697">?нш? опитування 
            на&nbsp;&nbsp;сайт? Черн?вецького м?ського л?цею №1</A> </FONT></B> 
          </TD>
</TR>
</TABLE>