<table border="0" width="100%" height="1" cellspacing="0" cellpadding="0">
  <tr bgcolor="#E3E5BA">
    <td width="80"></td>
    <td width="100%" height="34">
	<font color="#400080"><small><center>
   <a href="/main.shtml">Главная страница</a>
 | <a href="/news.shtml">Новости</a>
 | <a href="/contacts.shtml">Контакты</a>
 | <a href="http://www.guestbook.ru/book.cgi?user=lyceum1&amp;action=show">Гостевая книга</a>
 | <a href="/rest.shtml">Досуг</a>
 | <a href="/cross.shtml">Перекресток</a>
 | <a href="/job.shtml">Работа</a>
 | <a href="/lyrics.shtml">Уголок меломана</a>
 | <a href="/lyceum.shtml">Лицей - официоз</a>
 | <a href="/photo.shtml">Наши фотки</a>
 | <a href="/voting.shtml">Голосования</a>
 | <a href="http://pub12.bravenet.com/forum/show.php?usernum=981880309&cpv=1">Форум</a>
	</center> </small></font>
	</td>
  </tr>
  <tr bgcolor="#D3D5AA">
    <td width="80"></td>
    <td width="100%" height="34">
	<font color="#400080"><small>


<table width=180 height=35 border="0" cellspacing="0" cellpadding="0" align=right>  
<tr bgcolor="#D3D5AA">
<td>
<!-- SpyLOG v2 f:1211 --> 
<script language="javascript"> 
u="u915.68.spylog.com";d=document;nv=navigator;na=nv.appName;p=0;j="N"; 
d.cookie="b=b";c=0;bv=Math.round(parseFloat(nv.appVersion)*100); 
if (d.cookie) c=1;n=(na.substring(0,2)=="Mi")?0:1;rn=Math.random(); 
z="p="+p+"&rn="+rn+"&c="+c;if (self!=top) {fr=1;} else {fr=0;} 
sl="1.0";</script><script language="javascript1.1"> 
pl="";sl="1.1";j = (navigator.javaEnabled()?"Y":"N");</script> 
<script language=javascript1.2> 
sl="1.2";s=screen;px=(n==0)?s.colorDepth:s.pixelDepth; 
z+="&wh="+s.width+'x'+s.height+"&px="+px; 
</script><script language=javascript1.3> 
sl="1.3"</script><script language="javascript"> 
y="";y+="<a href='http://"+u+"/cnt?f=3&p="+p+"&rn="+rn+"' target=_blank>"; 
y+="<img src='http://"+u+"/cnt?"+z+"&j="+j+"&sl="+sl+ 
"&r1="+escape(d.referrer)+"&r="+escape(parent.document.referrer)+ 
"&fr="+fr+"&pg="+escape(window.location.href); 
y+="' border=0 width=88 height=31 alt='SpyLOG'>"; 
y+="</a>"; d.write(y);if(!n) { d.write("<"+"!--"); }//--></script><noscript> 
<a href="http://u915.68.spylog.com/cnt?f=3&p=0" target=_blank> 
<img src="http://u915.68.spylog.com/cnt?p=0" alt='SpyLOG' border='0' width=88 height=31> 
</a></noscript><script language="javascript1.2"><!-- 
if(!n) { d.write("--"+">"); }//--></script> 
<!-- SpyLOG -->
</td>
<td>
<!-- ECHO-Tracker (Type 7, 88x31) code. Begin --> 
    <a target="_top" href="http://tracker.echo.com.ua/tracker.asp?TrID=2046&amp;TTID=7">
	<script language="javascript">
    <!--
    un = Math.round((Math.random() * (2000000001)));
    document.write("<img src='http://tracker.echo.com.ua/gf.dll?counter?7&2046&"+un+"&"+escape(document.referrer)+"%20' height=31 width=88 border=0 alt='Echo'></a>");
    //-->
    </script> 
<!-- End ECHO-Tracker code --> 
</td>
</tr>
</table>
	this page was last updated <!--#echo var="LAST_MODIFIED"--> <br>
	designed by <a href="mailto:skalkin@usa.net">Andy Skalkin</a>.
	Please report all bugs etc. to <a href="mailto:lyceum_1@mail.ru?Subject=bugs">webmaster</a>
    </small></font></td>
  <tr>
<!-- Aport --><img src="http://www.ranker.ru/scripts/rcounter.dll?id=13356&amp;image=201" border="0" width="1" height="1"> <!-- End of Aport -->
<!--begin of Top100--><img src="http://counter.rambler.ru/top100.cnt?102722" width="1" height="1" border="0"><!--end of Top100 code-->  
  </tr>
</table>
