
<script language="JavaScript"><!--
 function TopMenuGoTo() {
  if (frmTopMenuGoto.D1.value!="")
  window.location.href=frmTopMenuGoto.D1.value;
 }
// --></script>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr>
 <td width="77"><img src="/images/lyceum.gif" alt="Лицей" width="100" height="106"></td>
 <td align="center">

<center><font size=-1>Благодарим за хостинг Черновицкий филиал Укртелекома</font></center><BR>

<a href="http://russian.wunderground.com/global/stations/33658.html">
<img src="http://banners.wunderground.com/banner/bigwx_metric_cond/language/russian/global/stations/33658.gif"
 alt="Click for Chernivtsi Forecast" border=0 height=60 width=468></a>



<br>		
<form name="frmTopMenuGoto">
  Перейти : 
    <select name="D1" size="1" onChange="TopMenuGoTo()">
      <option value="">Выберите нужную страницу ...</option>
      <option value="/main.shtml">Главная страница</option>
      <option value="/news.shtml">Новости</option>
      <option value="/contacts.shtml">Контакты</option>
      <option value="http://www.guestbook.ru/book.cgi?user=lyceum1&amp;action=show">Гостевая книга</option>
      <option value="/rest.shtml">Досуг</option>
      <option value="/cross.shtml">Перекресток</option>
      <option value="/job.shtml">Работа</option>
      <option value="/lyrics.shtml">Уголок меломана</option>
      <option value="/lyceum.shtml">Лицей - официоз</option>
      <option value="/photo.shtml">Наши фотки</option>
      <option value="/voting.shtml">Голосования</option>
      <option value="/index.htm">Страница с фреймами</option>
      <option value="http://pub12.bravenet.com/forum/show.php?usernum=981880309&cpv=1">Форум</option>
    </select>
  </form>
</td>
</tr>
</table>
