<!-- Begin List Poll HTML Code -->

<script language="JavaScript"><!--
 function VoteWindow() {
 window.open("http://www.voting.ru/cgi-bin/viewpoll.cgi?ID=11037","pollwindow",
 "toolbar=no,scrollbars=yes,directories=no,status=no,menubar=no,resizable=no,width=500,height=500")
 }
 // --></script>
<form ACTION="http://www.voting.ru/cgi-bin/viewpoll.cgi"
METHOD="POST" target="pollwindow" OnSubmit="VoteWindow()">
<input type="hidden" name="ID" value="11037">
<table border="1" width="153" bgcolor="#F4E6A1" cellpadding="3" 
cellspacing="0"><TR><TD bgcolor="#3366CC"><font color="#ffffff"><center>
Скажите честно</center></font></td></tr>
<tr><td><table border="0" cellpadding="0"><tr><td>
<font color="#000000">
Собираетесь ли вы эмигрировать из Украины ?</font><br><br>

<INPUT type="radio" name="vote" value="1">Да, собираюсь в скором времени. <BR>
<INPUT type="radio" name="vote" value="2">Нет, я уже там :) <BR>
<INPUT type="radio" name="vote" value="3">Нет, мне нравится жить в Украине <BR>
<INPUT type="radio" name="vote" value="4">Собираюсь после окончания учебы <BR>
<INPUT type="radio" name="vote" value="5">Я бы хотел, но у меня нет возможности <BR>
<INPUT type="radio" name="vote" value="6">Я хочу поработать за рубежом, а потом вернуться. <BR>
<br><br></td></tr></table>
</td></tr><tr><td align="center">
<input type="submit" value="Голосовать !" name="submit">
<small>
<a href="http://www.voting.ru/cgi-bin/viewpoll.cgi?ID=11037" OnClick="VoteWindow()" target="pollwindow">
<br>Текущие результаты</a></small></td></tr></table>
</form>

<!-- End List Poll HTML Code -->
