<!-- Begin List Poll HTML Code -->

<script language="JavaScript"><!--
 function VoteWindow() {
 window.open("http://www.voting.ru/cgi-bin/viewpoll.cgi?ID=11032","pollwindow",
 "toolbar=no,scrollbars=yes,directories=no,status=no,menubar=no,resizable=no,width=500,height=500")
 }
 // --></script>
<form ACTION="http://www.voting.ru/cgi-bin/viewpoll.cgi"
METHOD="POST" target="pollwindow" OnSubmit="VoteWindow()">
<input type="hidden" name="ID" value="11032">
<table border="1" width="153" bgcolor="#ddeeff" cellpadding="3" 
cellspacing="0"><TR><TD bgcolor="#5588cc"><font color="#ffffff"><center>
Скажите честно</center></font></td></tr>
<tr><td><table border="0" cellpadding="0"><tr><td>
<font color="#000000">
... скольких людей Вам удалось поиметь в качестве сексуальных партнеров ?  ;-)</font><br><br>

<INPUT type="radio" name="vote" value="1">ни одного, но я работаю над этим :) <BR>
<INPUT type="radio" name="vote" value="2">1 <BR>
<INPUT type="radio" name="vote" value="3">2-4 <BR>
<INPUT type="radio" name="vote" value="4">5-10 <BR>
<INPUT type="radio" name="vote" value="5">больше 10 (берегитесь !) <BR>
<INPUT type="radio" name="vote" value="6">у меня, наверное, ничего не получится ... <BR>
<br><br></td></tr></table>
</td></tr><tr><td align="center">
<input type="submit" value="Голосовать !" name="submit">
<small>
<a href="http://www.voting.ru/cgi-bin/viewpoll.cgi?ID=11032" OnClick="VoteWindow()" target="pollwindow">
<br>Текущие результаты</a></small></td></tr></table>
</form>

<!-- End List Poll HTML Code -->
