<!-- Begin List Poll HTML Code -->

<script language="JavaScript"><!--
 function VoteWindow() {
 window.open("http://www.voting.ru/cgi-bin/viewpoll.cgi?ID=11036","pollwindow",
 "toolbar=no,scrollbars=yes,directories=no,status=no,menubar=no,resizable=no,width=500,height=500")
 }
 // --></script>
<form ACTION="http://www.voting.ru/cgi-bin/viewpoll.cgi"
METHOD="POST" target="pollwindow" OnSubmit="VoteWindow()">
<input type="hidden" name="ID" value="11036">
<table border="1" width="153" bgcolor="#F0F0DF" cellpadding="3" 
cellspacing="0"><TR><TD bgcolor="#CDC477"><font color="#000000"><center>
Скажите-ка ...</center></font></td></tr>
<tr><td><table border="0" cellpadding="0"><tr><td>
<font color="#000000">
фильмы какого жанра Вам нравится смотреть больше всего ?</font><br><br>

<INPUT type="radio" name="vote" value="1">комедии (люблю похохотать ) <BR>
<INPUT type="radio" name="vote" value="2">боевики (мне нравятся здоровенные мужики) <BR>
<INPUT type="radio" name="vote" value="3">ужастики (обожаю слизь) <BR>
<INPUT type="radio" name="vote" value="4">порнографию (  ;-))  ) <BR>
<INPUT type="radio" name="vote" value="5">мыльные оперы (у меня много времени) <BR>
<INPUT type="radio" name="vote" value="6">мелодрамы (люблю всплакнуть) <BR>
<br><br></td></tr></table>
</td></tr><tr><td align="center">
<input type="submit" value="Голосовать !" name="submit">
<small>
<a href="http://www.voting.ru/cgi-bin/viewpoll.cgi?ID=11036" OnClick="VoteWindow()" target="pollwindow">
<br>Текущие результаты</a></small></td></tr></table>
</form>

<!-- End List Poll HTML Code -->
